[package]
authors = ["Fabio Kleis <fabiohkrc@gmail.com>"]
name = "rpdf"
version = "0.1.0"
edition = "2021"
 
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.32"
printpdf = "0.5.3"
